[package]
name = "wolfpack"
version = "0.1.0"
edition = "2021"

[dependencies]
ar = "0.9.0"
chrono = { version = "0.4.38", features = ["std"], default-features = false }
flate2 = "1.0.33"
hex = "0.4.3"
ksign = "0.1.0"
md5 = "0.7.0"
normalize-path = "0.2.1"
pgp = "0.14.0"
rand = "0.8.5"
rand_mt = "4.2.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sha1 = "0.10.6"
sha2 = "0.10.8"
smallvec = "1.13.2"
tar = { version = "0.4.42", features = [], default-features = false }
thiserror = "1.0.64"
walkdir = "2.5.0"
xz = "0.1.0"
zstd = "0.13.2"

[dev-dependencies]
arbitrary = { version = "1.3.2", features = ["derive", "derive_arbitrary"] }
arbtest = "0.3.1"
tempfile = "3.13.0"
