[package]
name = "wolfpack"
version = "0.1.0"
edition = "2021"

[dependencies]
ar = "0.9.0"
flate2 = "1.0.33"
tar = { version = "0.4.41", features = [], default-features = false }
thiserror = "1.0.64"
