[package]
name = "wolfpack"
version = "0.1.0"
edition = "2021"

[dependencies]
ar = "0.9.0"
flate2 = "1.0.33"
md5 = "0.7.0"
normalize-path = "0.2.1"
sha1 = "0.10.6"
sha2 = "0.10.8"
tar = { version = "0.4.42", features = [], default-features = false }
thiserror = "1.0.64"
walkdir = "2.5.0"
xz = "0.1.0"
