[alias]
test-deb = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-debian:latest\"",
    "--",
    "--nocapture",
    "--ignored",
    "dpkg",
    "apt",
]
test-ipk = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-openwrt:23.05.5\"",
    "--",
    "--nocapture",
    "--ignored",
    "opkg",
]
test-bsd-pkg = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-freebsd:latest\"",
    "--",
    "--nocapture",
    "--ignored",
    "bsd_pkg",
]
test-rpm = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh fedora:40\"",
    "--",
    "--nocapture",
    "--ignored",
    "rpm",
    "dnf",
]
test-macos = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-darling:latest\"",
    "--",
    "--nocapture",
    "--ignored",
    "macos",
]
test-wine = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-wine:latest\"",
    "--",
    "--nocapture",
    "--ignored",
    "msixmgr",
]
