[alias]
test-deb = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-debian:latest\"",
    "--",
    "--nocapture",
    "--ignored",
    "dpkg",
    "apt",
]
test-ipk = [
    "test",
    "--lib",
    "--config",
    "target.'cfg(target_os = \"linux\")'.runner=\"./ci/runner.sh ghcr.io/igankevich/wolfpack-ci-openwrt:23.05.5\"",
    "--",
    "--nocapture",
    "--ignored",
    "opkg",
]
