FROM debian:bookworm

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq install -y dpkg-dev debsig-verify lintian \
    && rm -rf /var/lib/apt/lists/*

LABEL org.opencontainers.image.source=https://github.com/igankevich/wolfpack
LABEL org.opencontainers.image.description="CI image"
