---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Log in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }}
          --password-stdin
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: ./ci/test.sh
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./ci/build.sh
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: ./ci/publish.sh
